//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sale
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailORDER
    {
        public int detailID { get; set; }
        public string voucherID { get; set; }
        public string productID { get; set; }
        public Nullable<int> number { get; set; }
    
        public virtual ORDER ORDER { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
