//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sale
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.DetailORDERs = new HashSet<DetailORDER>();
        }
    
        public string productID { get; set; }
        public string name { get; set; }
        public string detail { get; set; }
        public Nullable<decimal> price { get; set; }
        public string typeID { get; set; }
        public string producerID { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<int> saleCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailORDER> DetailORDERs { get; set; }
        public virtual PRODUCER PRODUCER { get; set; }
        public virtual TYPE TYPE { get; set; }
    }
}
